spring.data.mongodb.database=testdb
spring.main.allow-bean-definition-overriding=true
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

# CRITICAL: completely override schema
spring.jpa.properties.hibernate.default_schema=

spring.flyway.enabled=false